BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "couriers" (
	"courier_id"	INTEGER,
	"first_name"	TEXT NOT NULL,
	"last_name"	TEXT NOT NULL,
	"phone"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("courier_id")
);
CREATE TABLE IF NOT EXISTS "customers" (
	"customer_id"	INTEGER,
	"first_name"	TEXT NOT NULL,
	"last_name"	TEXT NOT NULL,
	"phone"	TEXT NOT NULL UNIQUE,
	"email"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("customer_id")
);
CREATE TABLE IF NOT EXISTS "delliveries" (
	"dellivery_id"	INTEGER,
	"order_id"	INTEGER NOT NULL,
	"courier_id"	INTEGER NOT NULL,
	"dellivery_address"	TEXT NOT NULL,
	"dellivery_date"	TEXT NOT NULL,
	"dellivery_status"	TEXT NOT NULL,
	PRIMARY KEY("dellivery_id"),
	FOREIGN KEY("courier_id") REFERENCES "couriers"("courier_id"),
	FOREIGN KEY("order_id") REFERENCES "orders"("order_id")
);
CREATE TABLE IF NOT EXISTS "order_items" (
	"order_item_id"	INTEGER,
	"order_id"	INTEGER NOT NULL,
	"product_id"	INTEGER NOT NULL,
	"quantity"	INTEGER NOT NULL,
	"price"	REAL NOT NULL,
	PRIMARY KEY("order_item_id"),
	FOREIGN KEY("order_id") REFERENCES "orders"("order_id"),
	FOREIGN KEY("product_id") REFERENCES "products"("product_id")
);
CREATE TABLE IF NOT EXISTS "orders" (
	"order_id"	INTEGER,
	"customer_id"	INTEGER NOT NULL,
	"order_date"	TEXT NOT NULL,
	"order_status"	TEXT NOT NULL,
	PRIMARY KEY("order_id"),
	FOREIGN KEY("customer_id") REFERENCES "customers"("customer_id")
);
CREATE TABLE IF NOT EXISTS "payments" (
	"payment_id"	INTEGER,
	"order_id"	INTEGER NOT NULL,
	"payment_date"	TEXT NOT NULL,
	"amount"	REAL NOT NULL,
	"payment_status"	TEXT NOT NULL,
	PRIMARY KEY("payment_id"),
	FOREIGN KEY("order_id") REFERENCES "orders"("order_id")
);
CREATE TABLE IF NOT EXISTS "products" (
	"product_id"	INTEGER,
	"product_name"	TEXT NOT NULL,
	"price"	REAL NOT NULL,
	PRIMARY KEY("product_id")
);
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (1,'Валерій','Чиж','+380632139591');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (2,'Андрій','Мироник','+380966643564');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (3,'Сергій','Семенюк','+380936899876');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (4,'Дмитро','Мельник','501000004');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (5,'Сергій','Ткаченко','501000005');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (6,'Іван','Кравченко','501000006');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (7,'Микола','Олійник','501000007');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (8,'Віталій','Шевчук','501000008');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (9,'Роман','Поліщук','501000009');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (10,'Богдан','Ковальчук','501000010');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (11,'Владислав','Мороз','501000011');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (12,'Артем','Лисенко','501000012');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (13,'Євген','Савченко','501000013');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (14,'Тарас','Романюк','501000014');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (15,'Юрій','Гнатюк','501000015');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (16,'Павло','Мазур','501000016');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (17,'Василь','Кушнір','501000017');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (18,'Олег','Петренко','501000018');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (19,'Степан','Данилюк','501000019');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (20,'Віктор','Захарченко','501000020');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (21,'Ігор','Бойко','501000021');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (22,'Михайло','Костенко','501000022');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (23,'Назар','Сидоренко','501000023');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (24,'Ярослав','Марченко','501000024');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (25,'Вадим','Руденко','501000025');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (26,'Олексій','Кравець','501000026');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (27,'Денис','Зінченко','501000027');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (28,'Артур','Ткачук','501000028');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (29,'Кирило','Дорошенко','501000029');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (30,'Матвій','Паламарчук','501000030');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (31,'Станіслав','Клименко','501000031');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (32,'Руслан','Власенко','501000032');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (33,'Володимир','Гриценко','501000033');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (34,'Антон','Левченко','501000034');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (35,'Роман','Черненко','501000035');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (36,'Ілля','Захарчук','501000036');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (37,'Леонід','Кириленко','501000037');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (38,'Гліб','Пархоменко','501000038');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (39,'Валерій','Коваль','501000039');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (40,'Анатолій','Білик','501000040');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (41,'Катерина','Шевченко','501000041');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (42,'Олена','Коваленко','501000042');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (43,'Наталія','Бондаренко','501000043');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (44,'Марія','Мельник','501000044');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (45,'Ірина','Ткаченко','501000045');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (46,'Оксана','Кравченко','501000046');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (47,'Тетяна','Олійник','501000047');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (48,'Світлана','Шевчук','501000048');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (49,'Анна','Поліщук','501000049');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (50,'Юлія','Ковальчук','501000050');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (51,'Вікторія','Мороз','501000051');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (52,'Анастасія','Лисенко','501000052');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (53,'Дарина','Савченко','501000053');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (54,'Софія','Романюк','501000054');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (55,'Христина','Гнатюк','501000055');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (56,'Людмила','Мазур','501000056');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (57,'Надія','Кушнір','501000057');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (58,'Лариса','Петренко','501000058');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (59,'Валентина','Данилюк','501000059');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (60,'Галина','Захарченко','501000060');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (61,'Алла','Бойко','501000061');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (62,'Віра','Костенко','501000062');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (63,'Лілія','Сидоренко','501000063');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (64,'Зоряна','Марченко','501000064');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (65,'Олеся','Руденко','501000065');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (66,'Яна','Кравець','501000066');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (67,'Поліна','Зінченко','501000067');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (68,'Віра','Ткачук','501000068');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (69,'Леся','Дорошенко','501000069');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (70,'Марина','Паламарчук','501000070');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (71,'Інна','Клименко','501000071');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (72,'Карина','Власенко','501000072');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (73,'Варвара','Гриценко','501000073');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (74,'Єлизавета','Левченко','501000074');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (75,'Соломія','Черненко','501000075');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (76,'Роксолана','Захарчук','501000076');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (77,'Мирослава','Кириленко','501000077');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (78,'Дарія','Пархоменко','501000078');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (79,'Людмила','Коваль','501000079');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (80,'Богдана','Білик','501000080');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (81,'Олександра','Шульга','501000081');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (82,'Вікторія','Гончаренко','501000082');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (83,'Аліна','Кузьменко','501000083');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (84,'Карина','Мельничук','501000084');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (85,'Інна','Романенко','501000085');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (86,'Тамара','Кучеренко','501000086');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (87,'Люба','Яремчук','501000087');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (88,'Сніжана','Василенко','501000088');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (89,'Маргарита','Гаврилюк','501000089');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (90,'Софія','Кравчук','501000090');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (91,'Ангеліна','Дяченко','501000091');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (92,'Віолетта','Остапенко','501000092');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (93,'Кіра','Капустян','501000093');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (94,'Аліса','Федоренко','501000094');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (95,'Мілана','Нечипоренко','501000095');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (96,'Злата','Вороненко','501000096');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (97,'Єва','Кравченко','501000097');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (98,'Дарина','Мельник','501000098');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (99,'Поліна','Семенюк','501000099');
INSERT INTO "couriers" ("courier_id","first_name","last_name","phone") VALUES (100,'Соломія','Коваленко','501000100');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (1,'Микола','Мартинов','+380364228118','martyn@ukr.net');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (2,'Іван','Петров','+380994438125','petyia@gmail.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (3,'Катерина','Іванішина','+380443845555','kateryna88@gmail.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (4,'customer4','Test4','+380500000004','customer4@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (5,'customer5','Test5','+380500000005','customer5@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (6,'customer6','Test6','+380500000006','customer6@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (7,'customer7','Test7','+380500000007','customer7@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (8,'customer8','Test8','+380500000008','customer8@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (9,'customer9','Test9','+380500000009','customer9@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (10,'customer10','Test10','+380500000010','customer10@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (11,'customer11','Test11','+380500000011','customer11@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (12,'customer12','Test12','+380500000012','customer12@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (13,'customer13','Test13','+380500000013','customer13@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (14,'customer14','Test14','+380500000014','customer14@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (15,'customer15','Test15','+380500000015','customer15@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (16,'customer16','Test16','+380500000016','customer16@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (17,'customer17','Test17','+380500000017','customer17@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (18,'customer18','Test18','+380500000018','customer18@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (19,'customer19','Test19','+380500000019','customer19@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (20,'customer20','Test20','+380500000020','customer20@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (21,'customer21','Test21','+380500000021','customer21@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (22,'customer22','Test22','+380500000022','customer22@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (23,'customer23','Test23','+380500000023','customer23@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (24,'customer24','Test24','+380500000024','customer24@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (25,'customer25','Test25','+380500000025','customer25@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (26,'customer26','Test26','+380500000026','customer26@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (27,'customer27','Test27','+380500000027','customer27@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (28,'customer28','Test28','+380500000028','customer28@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (29,'customer29','Test29','+380500000029','customer29@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (30,'customer30','Test30','+380500000030','customer30@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (31,'customer31','Test31','+380500000031','customer31@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (32,'customer32','Test32','+380500000032','customer32@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (33,'customer33','Test33','+380500000033','customer33@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (34,'customer34','Test34','+380500000034','customer34@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (35,'customer35','Test35','+380500000035','customer35@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (36,'customer36','Test36','+380500000036','customer36@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (37,'customer37','Test37','+380500000037','customer37@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (38,'customer38','Test38','+380500000038','customer38@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (39,'customer39','Test39','+380500000039','customer39@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (40,'customer40','Test40','+380500000040','customer40@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (41,'customer41','Test41','+380500000041','customer41@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (42,'customer42','Test42','+380500000042','customer42@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (43,'customer43','Test43','+380500000043','customer43@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (44,'customer44','Test44','+380500000044','customer44@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (45,'customer45','Test45','+380500000045','customer45@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (46,'customer46','Test46','+380500000046','customer46@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (47,'customer47','Test47','+380500000047','customer47@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (48,'customer48','Test48','+380500000048','customer48@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (49,'customer49','Test49','+380500000049','customer49@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (50,'customer50','Test50','+380500000050','customer50@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (51,'customer51','Test51','+380500000051','customer51@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (52,'customer52','Test52','+380500000052','customer52@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (53,'customer53','Test53','+380500000053','customer53@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (54,'customer54','Test54','+380500000054','customer54@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (55,'customer55','Test55','+380500000055','customer55@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (56,'customer56','Test56','+380500000056','customer56@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (57,'customer57','Test57','+380500000057','customer57@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (58,'customer58','Test58','+380500000058','customer58@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (59,'customer59','Test59','+380500000059','customer59@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (60,'customer60','Test60','+380500000060','customer60@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (61,'customer61','Test61','+380500000061','customer61@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (62,'customer62','Test62','+380500000062','customer62@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (63,'customer63','Test63','+380500000063','customer63@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (64,'customer64','Test64','+380500000064','customer64@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (65,'customer65','Test65','+380500000065','customer65@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (66,'customer66','Test66','+380500000066','customer66@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (67,'customer67','Test67','+380500000067','customer67@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (68,'customer68','Test68','+380500000068','customer68@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (69,'customer69','Test69','+380500000069','customer69@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (70,'customer70','Test70','+380500000070','customer70@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (71,'customer71','Test71','+380500000071','customer71@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (72,'customer72','Test72','+380500000072','customer72@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (73,'customer73','Test73','+380500000073','customer73@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (74,'customer74','Test74','+380500000074','customer74@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (75,'customer75','Test75','+380500000075','customer75@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (76,'customer76','Test76','+380500000076','customer76@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (77,'customer77','Test77','+380500000077','customer77@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (78,'customer78','Test78','+380500000078','customer78@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (79,'customer79','Test79','+380500000079','customer79@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (80,'customer80','Test80','+380500000080','customer80@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (81,'customer81','Test81','+380500000081','customer81@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (82,'customer82','Test82','+380500000082','customer82@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (83,'customer83','Test83','+380500000083','customer83@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (84,'customer84','Test84','+380500000084','customer84@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (85,'customer85','Test85','+380500000085','customer85@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (86,'customer86','Test86','+380500000086','customer86@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (87,'customer87','Test87','+380500000087','customer87@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (88,'customer88','Test88','+380500000088','customer88@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (89,'customer89','Test89','+380500000089','customer89@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (90,'customer90','Test90','+380500000090','customer90@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (91,'customer91','Test91','+380500000091','customer91@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (92,'customer92','Test92','+380500000092','customer92@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (93,'customer93','Test93','+380500000093','customer93@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (94,'customer94','Test94','+380500000094','customer94@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (95,'customer95','Test95','+380500000095','customer95@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (96,'customer96','Test96','+380500000096','customer96@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (97,'customer97','Test97','+380500000097','customer97@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (98,'customer98','Test98','+380500000098','customer98@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (99,'customer99','Test99','+380500000099','customer99@example.com');
INSERT INTO "customers" ("customer_id","first_name","last_name","phone","email") VALUES (100,'customer100','Test100','+380500000100','customer100@example.com');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (1,2,2,'м.Київ, вул. Васильківська 22/3','2026-04-15','Pending');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (2,1,3,'м.Рівне, вул. Соборна 253/178','2026-02-24','Dellivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (3,3,1,'м.Дніпро, вул. Степана Бандери 1/5','2026-06-10','Dellivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (4,4,7,'вул. Соборна 25, Рівне','2026-01-08','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (5,5,12,'вул. Шевченка 18, Львів','2026-01-11','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (6,6,3,'вул. Хрещатик 42, Київ','2026-01-14','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (7,7,18,'вул. Незалежності 67, Івано-Франківськ','2026-01-17','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (8,8,25,'вул. Грушевського 15, Луцьк','2026-01-20','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (9,9,9,'вул. Героїв України 31, Вінниця','2026-01-23','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (10,10,31,'вул. Соборності 56, Полтава','2026-01-26','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (11,11,15,'вул. Дорошенка 24, Львів','2026-01-29','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (12,12,22,'вул. Перемоги 38, Житомир','2026-02-02','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (13,13,6,'вул. Центральна 75, Тернопіль','2026-02-05','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (14,14,28,'вул. Київська 44, Рівне','2026-02-08','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (15,15,11,'вул. Княгині Ольги 29, Львів','2026-02-11','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (16,16,35,'вул. Чорновола 83, Луцьк','2026-02-14','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (17,17,4,'вул. Котляревського 16, Рівне','2026-02-17','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (18,18,19,'вул. Мазепи 51, Івано-Франківськ','2026-02-20','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (19,19,27,'вул. Замкова 12, Луцьк','2026-02-23','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (20,20,8,'вул. Бандери 64, Львів','2026-02-26','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (21,21,14,'вул. Київська 91, Житомир','2026-03-01','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (22,22,33,'вул. Володимирська 28, Київ','2026-03-04','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (23,23,5,'вул. Шухевича 47, Рівне','2026-03-07','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (24,24,17,'вул. Кривий Вал 32, Луцьк','2026-03-10','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (25,25,21,'вул. Франка 73, Львів','2026-03-13','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (26,26,30,'вул. Європейська 19, Полтава','2026-03-16','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (27,27,10,'вул. Дубнівська 88, Рівне','2026-03-19','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (28,28,24,'вул. Лесі Українки 41, Луцьк','2026-03-22','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (29,29,36,'вул. Князя Романа 27, Львів','2026-03-25','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (30,30,13,'вул. Данила Галицького 35, Рівне','2026-03-28','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (31,31,29,'вул. Зелена 62, Львів','2026-03-31','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (32,32,2,'вул. Театральна 14, Луцьк','2026-04-03','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (33,33,16,'вул. Грушевського 45, Тернопіль','2026-04-06','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (34,34,32,'вул. Князя Володимира 101, Рівне','2026-04-09','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (35,35,20,'вул. Лермонтова 18, Рівне','2026-04-12','Cancelled');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (36,36,7,'вул. Відінська 75, Рівне','2026-04-15','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (37,37,26,'вул. Шевченка 92, Чернівці','2026-04-18','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (38,38,12,'вул. Стрийська 145, Львів','2026-04-21','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (39,39,3,'вул. Руська 18, Тернопіль','2026-04-24','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (40,40,18,'вул. Київська 32, Рівне','2026-04-27','In Transit');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (41,41,25,'вул. Залізнична 17, Львів','2026-04-30','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (42,42,9,'вул. Шевченка 66, Житомир','2026-05-03','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (43,43,31,'вул. Степана Бандери 24, Рівне','2026-05-06','Failed');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (44,44,15,'вул. Винниченка 53, Львів','2026-05-09','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (45,45,22,'вул. Ковельська 9, Луцьк','2026-05-12','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (46,46,6,'вул. Княгині Ольги 78, Львів','2026-05-15','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (47,47,28,'вул. Шевченка 34, Рівне','2026-05-18','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (48,48,11,'вул. Галицька 42, Івано-Франківськ','2026-05-21','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (49,49,35,'вул. Драгоманова 19, Рівне','2026-05-24','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (50,50,4,'вул. Соборна 112, Луцьк','2026-05-27','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (51,51,19,'вул. Володимирська 67, Київ','2026-05-30','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (52,52,27,'вул. Ольжича 15, Житомир','2026-06-02','Cancelled');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (53,53,8,'вул. Садова 29, Рівне','2026-06-05','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (54,54,14,'вул. Кафедральна 12, Луцьк','2026-06-08','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (55,55,33,'вул. Володимира Великого 22, Львів','2026-06-11','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (56,56,5,'вул. Соборна 68, Рівне','2026-06-14','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (57,57,17,'вул. Київська 44, Житомир','2026-06-17','Pending');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (58,58,21,'вул. Січових Стрільців 36, Івано-Франківськ','2026-06-20','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (59,59,30,'вул. Костюшка 25, Львів','2026-06-23','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (60,60,10,'вул. Богоявленська 91, Рівне','2026-06-26','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (61,61,24,'вул. Київська 58, Житомир','2026-06-29','Failed');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (62,62,36,'вул. Грушевського 73, Луцьк','2026-07-02','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (63,63,13,'вул. Литовська 16, Луцьк','2026-07-05','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (64,64,29,'вул. Княгині Ольги 48, Львів','2026-07-08','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (65,65,2,'вул. Шевченка 27, Тернопіль','2026-07-11','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (66,66,16,'вул. Соборна 83, Рівне','2026-07-14','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (67,67,32,'вул. Незалежності 144, Івано-Франківськ','2026-07-17','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (68,68,20,'вул. Галицька 51, Львів','2026-07-20','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (69,69,7,'вул. Дубенська 38, Рівне','2026-07-23','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (70,70,26,'вул. Князя Романа 11, Львів','2026-07-26','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (71,71,12,'вул. Бандери 102, Луцьк','2026-07-29','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (72,72,3,'вул. Ковельська 65, Луцьк','2026-08-01','In Transit');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (73,73,18,'вул. Волинська 22, Рівне','2026-08-04','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (74,74,25,'вул. Шевченка 14, Тернопіль','2026-08-07','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (75,75,9,'вул. Коротка 7, Рівне','2026-08-10','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (76,76,31,'вул. Степана Бандери 31, Львів','2026-08-13','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (77,77,15,'вул. Соборна 18, Рівне','2026-08-16','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (78,78,22,'вул. Вітовського 44, Львів','2026-08-19','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (79,79,6,'вул. Січових Стрільців 118, Івано-Франківськ','2026-08-22','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (80,80,28,'вул. Борщівська 91, Тернопіль','2026-08-25','Cancelled');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (81,81,11,'вул. Княгині Ольги 72, Львів','2026-08-28','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (82,82,35,'вул. Київська 88, Рівне','2026-08-31','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (83,83,4,'вул. Липинського 132, Львів','2026-09-03','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (84,84,19,'вул. Гайдамацька 42, Луцьк','2026-09-06','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (85,85,27,'вул. Князя Володимира 121, Рівне','2026-09-09','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (86,86,8,'вул. Ольжича 17, Житомир','2026-09-12','Failed');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (87,87,14,'вул. Соборна 54, Рівне','2026-09-15','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (88,88,33,'вул. Городоцька 29, Львів','2026-09-18','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (89,89,5,'вул. Словацького 64, Рівне','2026-09-21','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (90,90,17,'вул. Рильського 21, Луцьк','2026-09-24','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (91,91,21,'вул. Чорновола 37, Львів','2026-09-27','Pending');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (92,92,30,'вул. Драгоманова 15, Рівне','2026-09-30','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (93,93,10,'вул. Соборна 73, Луцьк','2026-10-03','Delivered');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (94,94,24,'вул. Хрещатик 48, Київ','2026-10-06','In Transit');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (95,95,36,'вул. Шевченка 91, Рівне','2026-10-09','Pending');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (96,96,13,'вул. Стрийська 114, Львів','2026-10-12','Pending');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (97,97,29,'вул. Соборна 36, Тернопіль','2026-10-15','In Transit');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (98,98,2,'вул. Незалежності 52, Івано-Франківськ','2026-10-18','Pending');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (99,99,16,'вул. Тараса Шевченка 67, Рівне','2026-10-21','Pending');
INSERT INTO "delliveries" ("dellivery_id","order_id","courier_id","dellivery_address","dellivery_date","dellivery_status") VALUES (100,100,32,'вул. Степана Бандери 145, Львів','2026-10-24','Pending');
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (1,1,2,2,7099.98);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (2,2,3,1,5789.49);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (3,3,1,4,153999.96);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (4,4,7,2,24.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (5,5,12,1,89.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (6,6,3,3,14.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (7,7,18,1,129.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (8,8,25,2,39.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (9,9,9,1,59.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (10,10,31,4,12.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (11,11,15,1,74.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (12,12,22,2,45.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (13,13,6,1,199.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (14,14,28,3,19.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (15,15,11,1,34.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (16,16,35,2,79.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (17,17,4,1,109.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (18,18,19,2,29.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (19,19,27,1,159.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (20,20,8,3,22.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (21,21,14,1,49.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (22,22,33,2,64.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (23,23,5,1,249.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (24,24,17,2,31.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (25,25,21,1,99.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (26,26,30,3,17.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (27,27,10,1,44.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (28,28,24,2,55.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (29,29,36,1,139.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (30,30,13,4,11.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (31,31,29,1,69.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (32,32,2,2,27.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (33,33,16,1,119.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (34,34,32,3,23.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (35,35,20,1,89.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (36,36,7,2,24.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (37,37,26,1,179.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (38,38,12,3,89.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (39,39,3,2,14.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (40,40,18,1,129.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (41,41,25,1,39.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (42,42,9,2,59.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (43,43,31,1,12.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (44,44,15,3,74.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (45,45,22,1,45.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (46,46,6,2,199.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (47,47,28,1,19.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (48,48,11,2,34.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (49,49,35,1,79.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (50,50,4,3,109.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (51,51,19,1,29.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (52,52,27,2,159.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (53,53,8,1,22.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (54,54,14,2,49.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (55,55,33,1,64.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (56,56,5,2,249.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (57,57,17,1,31.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (58,58,21,3,99.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (59,59,30,1,17.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (60,60,10,2,44.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (61,61,24,1,55.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (62,62,36,2,139.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (63,63,13,1,11.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (64,64,29,3,69.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (65,65,2,1,27.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (66,66,16,2,119.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (67,67,32,1,23.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (68,68,20,2,89.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (69,69,7,1,24.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (70,70,26,3,179.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (71,71,12,1,89.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (72,72,3,2,14.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (73,73,18,1,129.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (74,74,25,3,39.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (75,75,9,1,59.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (76,76,31,2,12.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (77,77,15,1,74.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (78,78,22,2,45.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (79,79,6,1,199.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (80,80,28,4,19.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (81,81,11,1,34.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (82,82,35,2,79.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (83,83,4,1,109.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (84,84,19,3,29.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (85,85,27,1,159.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (86,86,8,2,22.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (87,87,14,1,49.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (88,88,33,2,64.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (89,89,5,1,249.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (90,90,17,3,31.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (91,91,21,1,99.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (92,92,30,2,17.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (93,93,10,1,44.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (94,94,24,2,55.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (95,95,36,1,139.9);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (96,96,13,3,11.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (97,97,29,1,69.99);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (98,98,2,2,27.5);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (99,99,16,1,119.0);
INSERT INTO "order_items" ("order_item_id","order_id","product_id","quantity","price") VALUES (100,100,32,2,23.9);
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (1,1,'2026-02-21','Shipping');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (2,2,'2026-04-12','Pending');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (3,3,'2026-06-28','Dellivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (4,63,'2026-01-10','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (5,25,'2026-01-12','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (6,91,'2026-01-14','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (7,34,'2026-01-16','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (8,76,'2026-01-18','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (9,5,'2026-01-20','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (10,58,'2026-01-22','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (11,12,'2026-01-24','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (12,87,'2026-01-26','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (13,49,'2026-01-28','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (14,31,'2026-01-30','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (15,69,'2026-02-01','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (16,3,'2026-02-03','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (17,55,'2026-02-05','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (18,94,'2026-02-07','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (19,21,'2026-02-09','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (20,72,'2026-02-11','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (21,44,'2026-02-13','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (22,16,'2026-02-15','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (23,83,'2026-02-17','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (24,38,'2026-02-19','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (25,61,'2026-02-21','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (26,7,'2026-02-23','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (27,29,'2026-02-25','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (28,96,'2026-02-27','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (29,53,'2026-03-01','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (30,11,'2026-03-03','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (31,67,'2026-03-05','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (32,24,'2026-03-07','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (33,89,'2026-03-09','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (34,46,'2026-03-11','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (35,14,'2026-03-13','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (36,78,'2026-03-15','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (37,35,'2026-03-17','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (38,62,'2026-03-19','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (39,2,'2026-03-21','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (40,51,'2026-03-23','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (41,97,'2026-03-25','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (42,19,'2026-03-27','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (43,74,'2026-03-29','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (44,40,'2026-03-31','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (45,6,'2026-04-02','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (46,86,'2026-04-04','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (47,28,'2026-04-06','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (48,65,'2026-04-08','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (49,13,'2026-04-10','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (50,57,'2026-04-12','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (51,81,'2026-04-14','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (52,32,'2026-04-16','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (53,93,'2026-04-18','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (54,47,'2026-04-20','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (55,22,'2026-04-22','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (56,70,'2026-04-24','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (57,9,'2026-04-26','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (58,59,'2026-04-28','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (59,36,'2026-04-30','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (60,84,'2026-05-02','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (61,27,'2026-05-04','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (62,73,'2026-05-06','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (63,15,'2026-05-08','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (64,48,'2026-05-10','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (65,99,'2026-05-12','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (66,4,'2026-05-14','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (67,66,'2026-05-16','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (68,30,'2026-05-18','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (69,52,'2026-05-20','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (70,18,'2026-05-22','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (71,45,'2026-05-24','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (72,90,'2026-05-26','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (73,37,'2026-05-28','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (74,80,'2026-05-30','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (75,10,'2026-06-01','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (76,56,'2026-06-03','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (77,68,'2026-06-05','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (78,23,'2026-06-07','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (79,85,'2026-06-09','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (80,43,'2026-06-11','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (81,71,'2026-06-13','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (82,98,'2026-06-15','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (83,26,'2026-06-17','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (84,60,'2026-06-19','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (85,33,'2026-06-21','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (86,88,'2026-06-23','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (87,20,'2026-06-25','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (88,79,'2026-06-27','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (89,41,'2026-06-29','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (90,95,'2026-07-01','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (91,64,'2026-07-03','Cancelled');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (92,1,'2026-07-05','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (93,54,'2026-07-07','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (94,82,'2026-07-09','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (95,39,'2026-07-11','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (96,92,'2026-07-13','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (97,50,'2026-07-15','Shipped');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (98,75,'2026-07-17','Delivered');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (99,100,'2026-07-19','Processing');
INSERT INTO "orders" ("order_id","customer_id","order_date","order_status") VALUES (100,57,'2026-07-21','Delivered');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (1,2,'2026-04-12',7099.98,'Pending');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (2,1,'2026-02-21',7099.98,'Paind');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (3,3,'2026-06-28',153999.96,'Paind');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (4,4,'2026-01-06',49.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (5,5,'2026-01-09',89.5,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (6,6,'2026-01-12',44.97,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (7,7,'2026-01-15',129.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (8,8,'2026-01-18',79.8,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (9,9,'2026-01-21',59.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (10,10,'2026-01-24',50.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (11,11,'2026-01-27',74.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (12,12,'2026-01-30',90.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (13,13,'2026-02-02',199.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (14,14,'2026-02-05',59.7,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (15,15,'2026-02-08',34.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (16,16,'2026-02-11',158.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (17,17,'2026-02-14',109.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (18,18,'2026-02-17',59.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (19,19,'2026-02-20',159.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (20,20,'2026-02-23',68.97,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (21,21,'2026-02-26',49.9,'Pending');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (22,22,'2026-03-01',129.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (23,23,'2026-03-04',249.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (24,24,'2026-03-07',63.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (25,25,'2026-03-10',99.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (26,26,'2026-03-13',52.5,'Failed');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (27,27,'2026-03-16',44.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (28,28,'2026-03-19',110.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (29,29,'2026-03-22',139.9,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (30,30,'2026-03-25',47.96,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (31,31,'2026-03-28',69.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (32,32,'2026-03-31',55.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (33,33,'2026-04-03',119.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (34,34,'2026-04-06',71.7,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (35,35,'2026-04-09',89.99,'Refunded');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (36,36,'2026-04-12',49.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (37,37,'2026-04-15',179.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (38,38,'2026-04-18',268.5,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (39,39,'2026-04-21',29.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (40,40,'2026-04-24',129.0,'Pending');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (41,41,'2026-04-27',39.9,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (42,42,'2026-04-30',119.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (43,43,'2026-05-03',12.5,'Failed');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (44,44,'2026-05-06',224.97,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (45,45,'2026-05-09',45.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (46,46,'2026-05-12',398.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (47,47,'2026-05-15',19.9,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (48,48,'2026-05-18',69.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (49,49,'2026-05-21',79.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (50,50,'2026-05-24',329.97,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (51,51,'2026-05-27',29.5,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (52,52,'2026-05-30',318.0,'Refunded');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (53,53,'2026-06-02',22.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (54,54,'2026-06-05',99.8,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (55,55,'2026-06-08',64.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (56,56,'2026-06-11',498.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (57,57,'2026-06-14',31.99,'Pending');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (58,58,'2026-06-17',297.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (59,59,'2026-06-20',17.5,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (60,60,'2026-06-23',89.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (61,61,'2026-06-26',55.0,'Failed');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (62,62,'2026-06-29',279.8,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (63,63,'2026-07-02',11.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (64,64,'2026-07-05',209.97,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (65,65,'2026-07-08',27.5,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (66,66,'2026-07-11',238.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (67,67,'2026-07-14',23.9,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (68,68,'2026-07-17',179.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (69,69,'2026-07-20',24.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (70,70,'2026-07-23',537.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (71,71,'2026-07-26',89.5,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (72,72,'2026-07-29',29.98,'Pending');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (73,73,'2026-08-01',129.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (74,74,'2026-08-04',119.7,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (75,75,'2026-08-07',59.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (76,76,'2026-08-10',25.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (77,77,'2026-08-13',74.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (78,78,'2026-08-16',90.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (79,79,'2026-08-19',199.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (80,80,'2026-08-22',79.6,'Refunded');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (81,81,'2026-08-25',34.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (82,82,'2026-08-28',158.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (83,83,'2026-08-31',109.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (84,84,'2026-09-03',88.5,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (85,85,'2026-09-06',159.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (86,86,'2026-09-09',45.98,'Failed');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (87,87,'2026-09-12',49.9,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (88,88,'2026-09-15',129.98,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (89,89,'2026-09-18',249.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (90,90,'2026-09-21',95.97,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (91,91,'2026-09-24',99.0,'Pending');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (92,92,'2026-09-27',35.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (93,93,'2026-09-30',44.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (94,94,'2026-10-03',110.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (95,95,'2026-10-06',139.9,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (96,96,'2026-10-09',35.97,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (97,97,'2026-10-12',69.99,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (98,98,'2026-10-15',55.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (99,99,'2026-10-18',119.0,'Paid');
INSERT INTO "payments" ("payment_id","order_id","payment_date","amount","payment_status") VALUES (100,100,'2026-10-21',47.8,'Paid');
INSERT INTO "products" ("product_id","product_name","price") VALUES (1,'ноутбук',38499.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (2,'бездротові_навушники',3549.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (3,'принтер',5789.49);
INSERT INTO "products" ("product_id","product_name","price") VALUES (4,'USB Cable',12.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (5,'Power Bank',39.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (6,'Wireless Charger',24.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (7,'Smart Watch',129.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (8,'Tablet',299.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (9,'Monitor',189.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (10,'Webcam',59.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (11,'Microphone',89.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (12,'Printer',149.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (13,'Router',79.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (14,'External Hard Drive',74.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (15,'SSD Drive',99.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (16,'USB Flash Drive',14.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (17,'Memory Card',11.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (18,'Laptop Bag',34.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (19,'Wireless Mouse',27.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (20,'Mechanical Keyboard',69.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (21,'Gaming Mouse',44.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (22,'Gaming Keyboard',84.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (23,'Gaming Headset',59.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (24,'Bluetooth Speaker',49.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (25,'Earbuds',39.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (26,'HDMI Cable',9.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (27,'DisplayPort Cable',12.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (28,'Phone Case',15.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (29,'Screen Protector',8.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (30,'Car Charger',19.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (31,'Phone Holder',17.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (32,'Smartphone Stand',13.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (33,'Desk Lamp',29.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (34,'LED Strip',18.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (35,'Power Strip',22.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (36,'Extension Cord',16.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (37,'Surge Protector',31.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (38,'Bluetooth Adapter',14.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (39,'Wi-Fi Adapter',21.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (40,'USB Hub',26.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (41,'Laptop Stand',32.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (42,'Cooling Pad',28.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (43,'Laptop Charger',45.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (44,'Phone Charger',21.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (45,'USB-C Charger',29.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (46,'Smart TV',449.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (47,'TV Wall Mount',39.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (48,'Soundbar',159.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (49,'Digital Camera',499.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (50,'Camera Tripod',54.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (51,'Camera Bag',44.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (52,'Memory Card Reader',12.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (53,'Action Camera',219.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (54,'Game Controller',64.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (55,'Gaming Chair',179.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (56,'Gaming Desk',149.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (57,'Desk Organizer',19.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (58,'Office Chair',129.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (59,'Office Desk',199.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (60,'Notebook',6.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (61,'Wireless Presenter',24.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (62,'Barcode Scanner',89.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (63,'Label Printer',109.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (64,'Document Scanner',129.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (65,'Ink Cartridge',24.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (66,'Toner Cartridge',49.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (67,'Printer Paper',7.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (68,'Computer Speakers',34.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (69,'Subwoofer',79.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (70,'USB Microphone',54.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (71,'Studio Headphones',119.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (72,'Audio Interface',139.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (73,'Smart Home Hub',69.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (74,'Smart Bulb',14.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (75,'Smart Plug',16.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (76,'Security Camera',89.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (77,'Video Doorbell',119.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (78,'Robot Vacuum',299.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (79,'Air Purifier',159.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (80,'Electric Kettle',39.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (81,'Coffee Machine',199.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (82,'Blender',69.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (83,'Toaster',34.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (84,'Microwave Oven',129.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (85,'Electric Grill',99.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (86,'Digital Scale',24.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (87,'Fitness Tracker',79.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (88,'Electric Toothbrush',49.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (89,'Hair Dryer',44.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (90,'Shaver',59.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (91,'Portable Fan',29.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (92,'Air Humidifier',69.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (93,'Desk Clock',18.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (94,'Alarm Clock',15.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (95,'Backpack',49.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (96,'Travel Adapter',22.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (97,'Power Inverter',64.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (98,'Portable Projector',249.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (99,'Smart Projector',329.99);
INSERT INTO "products" ("product_id","product_name","price") VALUES (100,'Wireless Door Lock',149.99);
CREATE INDEX IF NOT EXISTS "idx_delliveries_courier_id" ON "delliveries" (
	"courier_id"
);
CREATE INDEX IF NOT EXISTS "idx_delliveries_order_id" ON "delliveries" (
	"order_id"
);
CREATE INDEX IF NOT EXISTS "idx_order_items_order_id" ON "order_items" (
	"order_id"
);
CREATE INDEX IF NOT EXISTS "idx_order_items_product_id" ON "order_items" (
	"product_id"
);
CREATE INDEX IF NOT EXISTS "idx_orders_customer_id" ON "orders" (
	"customer_id"
);
CREATE INDEX IF NOT EXISTS "idx_payments_order_id" ON "payments" (
	"order_id"
);
COMMIT;
